package io.contek.invoker.bitmex.api.common;

import javax.annotation.concurrent.NotThreadSafe;

@NotThreadSafe
public class _Position {

  public Long account;
  public String symbol;
  public String currency;
  public String underlying;
  public String quoteCurrency;
  public Double commission;
  public Double initMarginReq;
  public Double maintMarginReq;
  public Long riskLimit;
  public Double leverage;
  public Boolean crossMargin;
  public Double deleveragePercentile;
  public Long rebalancedPnl;
  public Long prevRealisedPnl;
  public Long prevUnrealisedPnl;
  public Double prevClosePrice;
  public String openingTimestamp;
  public Double openingQty;
  public Long openingCost;
  public Long openingComm;
  public Double openOrderBuyQty;
  public Long openOrderBuyCost;
  public Long openOrderBuyPremium;
  public Double openOrderSellQty;
  public Long openOrderSellCost;
  public Long openOrderSellPremium;
  public Double execBuyQty;
  public Long execBuyCost;
  public Double execSellQty;
  public Long execSellCost;
  public Double execQty;
  public Long execCost;
  public Long execComm;
  public String currentTimestamp;
  public Double currentQty;
  public Long currentCost;
  public Long currentComm;
  public Long realisedCost;
  public Long unrealisedCost;
  public Long grossOpenCost;
  public Long grossOpenPremium;
  public Long grossExecCost;
  public Boolean isOpen;
  public Double markPrice;
  public Long markValue;
  public Long riskValue;
  public Double homeNotional;
  public Double foreignNotional;
  public Long posCost;
  public Long posCost2;
  public Long posCross;
  public Long posInit;
  public Long posComm;
  public Long posLoss;
  public Long posMargin;
  public Long posMaint;
  public Long posAllowance;
  public Long taxableMargin;
  public Long initMargin;
  public Long maintMargin;
  public Long sessionMargin;
  public Long targetExcessMargin;
  public Long varMargin;
  public Long realisedGrossPnl;
  public Long realisedTax;
  public Long realisedPnl;
  public Long unrealisedGrossPnl;
  public Long unrealisedPnl;
  public Double unrealisedPnlPcnt;
  public Double unrealisedRoePcnt;
  public Double avgCostPrice;
  public Double avgEntryPrice;
  public Double breakEvenPrice;
  public Double marginCallPrice;
  public Double liquidationPrice;
  public Double bankruptPrice;
  public String timestamp;
  public Double lastPrice;
  public Long lastValue;
}
